export const CALCULATE = 'CALCULATE'
export const MAX = 'MAX'
export const MIN = 'MIN'
export const MULTIPLY = 'MULTIPLY'
export const DEVIDE = 'DEVIDE'
export const PERSEN = 'PERSEN'
export const CLEAR = 'CLEAR'
export const ALLCLEAR = 'ALLCLEAR'
export const NUMBER_7 ="NUMBER_7"
export const NUMBER_8 ="NUMBER_8"
export const NUMBER_9 ="NUMBER_9"
export const NUMBER_4 ="NUMBER_4"
export const NUMBER_5 ="NUMBER_5"
export const NUMBER_6 ="NUMBER_6"
export const NUMBER_1 ="NUMBER_1"
export const NUMBER_2 ="NUMBER_2"
export const NUMBER_3 ="NUMBER_3"
export const NUMBER_00 ="NUMBER_00"
export const NUMBER_0 ="NUMBER_0"
export const COMA ="COMA"